#!/bin/bash
<<doc
Description :Count the number of users with user IDs between given range.
Sample input :/user_ids.sh 0 100
sample output : Total count of user ID between 0 to 100 is : 3
doc

usr_id=(`cat /etc/passwd | cut -d ":" -f3`) #storing the userid in a variable
count=0
if [ $# -ne 0 ] #if input not equal to zero
then
     if [ $# -eq 2 ] #check wheather it has two input
     then
          if [ $1 -lt $2 ] #check wheather the first one is lower than second one
          then
	      for i in ${usr_id[@]} #taking for loop through the array storing the user id
	      do
		  if [ ${i} -gt $1 -a ${i} -lt $2 ] #checking the condition for less than and greaterthan condition
		  then
		      count=$(($count+1))
		  fi
	      done
	  else
	      echo "Error : Invalid range. Please enter the valid range through CL."
	  fi
	  echo "Total count of user ID between $1 to $2 is : $count"
      else
	  echo "Error : Please pass 2 arguments through CL."
          echo "Usage : ./user_ids.sh 100 200"
     fi
 else
     for i in ${usr_id[@]} #taking for loop through the array storing the user id
     do
	 if [ ${i} -gt 500 -a ${i} -lt 1000 ] #checking the general condition if no input is given
	 then
	     count=$(($count+1))
	 fi
     done
     echo "Total count of user ID between 500 to 10000 is: $count"

fi
