#!/bin/bash
<<doc
Description :script to determine whether a given file system or mount point is mounted
Sample input :./mounted_fs.sh /dev/sda2
sample output :File-system /dev/sda2 is mounted on / and it is having 98% used space with 3298220 KB free.
doc

file_sys=(`df | tr -s " " | cut -d " " -f1`) #storing the file 
available=(`df | tr -s " " | cut -d " " -f4`) #storing the available space in an array
used=(`df | tr -s " " | cut -d " " -f5`) #storing the used space in an array
mount=(`df | tr -s " " | cut -d " " -f6`) #storing the mounted on in an array
len=${#file_sys[@]} #storing the length
length=$(($len-1)) 
flag=0 #set flag as zero
if [ $# -eq 1 ]
then
    for i in `seq 1 1 $length #for loop from 1 to length-1`
    do
	if [ $1 = ${file_sys[i]} ] #if input equal to the input 
	then
	    flag=1 #set flag as 1
	    echo "File-system $1 is mounted on ${mount[i]} and it is having ${used[i]} used space with ${available[i]} KB free."
	fi
    done
    if [ $flag -eq 0 ] #check wheather the flag is zero or not
    then
	echo "$1 is not mounted."
    fi
else
    echo "Error : Please pass the name of the file-system through command line."
fi
